### ISSUE TITLE
如何自定义互动效果配置功能

### ISSUE THREAD

**Issue by Rinoex** [SprInec/typora-spring-theme#4]
你好，感谢您分享的森林配色主题。导出pdf效果十分美观！
请问在typora中对文件进行编辑的动画应该如何关闭呢？暂未在主题或设置中看到相关介绍。

**Comment by SprInec** [comment]
您好，很高兴您能喜欢 SprIng😊
关闭动画的方法在README_cn.md的 **自定义配置-交互效果配置** 有做说明，这里再向您说明下操作方法：
1. 打开 `spring,css` 文件
2. 在文件开头找到交互效果配置部分的代码，在 29 ~ 99 行, 内容如下
    ![image](https://github.com/user-attachments/assets/3c3fb9a7-7a56-4299-b4a1-89e4ecdb2974)
3. 根据注释提示可自行修改变量值进行自定义配置，默认是交互效果全部开启
    > **若您想关闭全部的交互效果，直接将第45行的`--use-dynamic-effect` 设置为 0， 将第 93行的 `--list-ol-text-style` 设置为 italic 即可。**
4. 重启 Typora 应用更改。

若您在操作过程中还有什么不明白的地方，欢迎随时提问~
