### ISSUE TITLE
How to use Alert blockquote ？

### ISSUE THREAD

**Issue by moreasy** [SprInec/typora-spring-theme#5]
> "> " is a sample blockquote syntax 

Please show me the demo code for Alert style blockquote

**Comment by SprInec** [comment]
Hello, in Typora, 5 different alter types are supported. You can add them by the following method:
`> [!tip]`  `> [!note]`  `> [!important]`  `> [!caution]`  `> [!warning]`

The above method also applies to Markdown files in GitHub，Their effects are as follows：
> [!tip]
> demo

> [!note]
> demo

> [!important]
> demo

> [!caution]
> demo

> [!warning]
> demo

If you have any other questions, please feel free to give us feedback.

**Comment by moreasy** [comment]
> [!tip] 
> Thanks, bro! My Typora version (1.4.8) was too low and didn't support GitHub-style alerts. 
> It's working now after upgrading to the latest version.
