### ISSUE TITLE
全文抖动

### ISSUE THREAD

**Issue by ocean-dragon** [SprInec/typora-spring-theme#7]
在正文中，鼠标点击正文最左端的光标（在开发者模式下观察到的是点击正文的左padding处就会触发），会导致全文抖动，每点击一次全文抖动一次；有时还会跳到随机上下文

**Comment by SprInec** [comment]
您好，感谢您的反馈❤

这边初步判断是由于段落交互动画对padding值的改变，以及文本两端对齐所引起的。

因无法看到具体的问题，为进一步判断与修复问题，请问能否提供一下 bug 的视频或者 gif 动画呢，如果可以的话，能否进一步提供出现 bug 的文本段落或者文档呢。可以发送给这个邮箱 julycubspring@gmail.com。非常感谢您的反馈与帮助。

**Comment by ocean-dragon** [comment]
好的，已经发送过去，好像现在点击又不会抖动了。有点奇怪。

**Comment by ocean-dragon** [comment]
好的，已经发送过去，好像现在点击又不会抖动了。有点奇怪。

**Comment by ocean-dragon** [comment]
嗯嗯是的，好像就是因为当时Typora卡顿了，后面我关闭重启软件后就没有出现了。感谢作者的耐心答复:D
