### ISSUE TITLE
如何移除移动到文件段落上的动态效果

### ISSUE THREAD

**Issue by Zhipeng-Li** [SprInec/typora-spring-theme#8]
如何移除移动到文件段落、图片、表格上的动态效果，其他地方都很完美，就是这个动态效果个人不是很喜欢，请问如何移除这个动态效果。

**Comment by SprInec** [comment]
您好，感谢您的反馈。

关闭动画的方法在 `README_cn.md` 的 自定义配置-交互效果配置 有做说明，这里再向您说明下操作方法：

打开 `spring.css` 文件
在文件开头找到交互效果配置部分的代码，大概位于 30 ~ 85 行,

根据注释提示可自行修改变量值进行自定义配置，默认是交互效果全部开启

文件段落交互的修改项在 43行
![image](https://github.com/user-attachments/assets/0eee4a3d-ead5-4816-8c1c-0b0a0eec6bf1)

图片的在46行
![image](https://github.com/user-attachments/assets/e840fd4b-4443-4ae5-bdb1-3bd479db620d)

表格的在 85行
![image](https://github.com/user-attachments/assets/bd92dc49-3d06-4ff8-b59c-77bc9689b1f8)

若您想关闭全部的交互效果，直接将第31行的--use-dynamic-effect 设置为 0， 将第 79行的 --list-ol-text-style 设置为 italic 即可。

重启 Typora 应用更改。
若您在操作过程中还有什么不明白的地方，欢迎随时提问~

**Comment by Zhipeng-Li** [comment]
非常感谢回复，以后我多多看readme。

**Comment by SprInec** [comment]
不客气哈，若后续使用过程中遇到什么问题，欢迎随时反馈🤗。
