### ISSUE TITLE
文档开头的一级标题没有加粗效果

### ISSUE THREAD

**Issue by spranaky** [SprInec/typora-spring-theme#9]
文档开头第一个一级标题没有加粗，后面的标题都有加粗效果。
![image](https://github.com/user-attachments/assets/4338c0ea-f025-41e8-9c6c-9fe756224139)
如果在开头空一行再写一级标题也能加粗。
![image](https://github.com/user-attachments/assets/e9dfb58a-1bee-4600-8b0c-dbcd7537dfff)
而且文档开头的二级、三级、四级标题都有加粗效果，就是一级标题没有。
![image](https://github.com/user-attachments/assets/c000690c-c94b-4c4d-98ed-08493593dac7)

**Comment by SprInec** [comment]
您好，感谢您的反馈😊，该问题现已修复，请下载最新的 `spring.css` 文件应用修改
